highlighter: pygments
encoding: utf-8
paginate: 6
paginate_path: "page:num"
markdown: redcarpet
redcarpet: 
    extensions: ["fenced_code_blocks", "tables", "highlight", "with_toc_data", "strikethrough", "underline"]