highlighter: rouge
gems: [jekyll-paginate]
encoding: utf-8
paginate: 8
paginate_path: "page:num"
markdown: kramdown
kramdown:
  syntax_highlighter: rouge

name: 写代码的猴子
description: 当猴子不写代码时,他在写些什么。
url: http://jaeger.itscoder.com/

defaults:
 -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"